package domain;
// Generated Jan 13, 2017 11:22:15 AM by Hibernate Tools 5.2.0.Beta1

/**
 * Cashier generated by hbm2java
 */
public class Cashier implements java.io.Serializable {

	private Integer id;
	private String cashierName;

	public Cashier() {
	}

	public Cashier(String cashierName) {
		this.cashierName = cashierName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCashierName() {
		return this.cashierName;
	}

	public void setCashierName(String cashierName) {
		this.cashierName = cashierName;
	}

}
