package domain;
// Generated Jan 13, 2017 11:22:15 AM by Hibernate Tools 5.2.0.Beta1

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer id;
	private String customerName;

	public Customer() {
	}

	public Customer(String customerName) {
		this.customerName = customerName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

}
