package domain;
// Generated Jan 13, 2017 11:22:15 AM by Hibernate Tools 5.2.0.Beta1

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private Integer id;
	private String itemName;
	private Integer itemCount;
	private Double itemPrice;

	public Item() {
	}

	public Item(String itemName) {
		this.itemName = itemName;
	}

	public Item(String itemName, Integer itemCount, Double itemPrice) {
		this.itemName = itemName;
		this.itemCount = itemCount;
		this.itemPrice = itemPrice;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Integer getItemCount() {
		return this.itemCount;
	}

	public void setItemCount(Integer itemCount) {
		this.itemCount = itemCount;
	}

	public Double getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(Double itemPrice) {
		this.itemPrice = itemPrice;
	}

}
