package domain;
// Generated Jan 13, 2017 11:22:15 AM by Hibernate Tools 5.2.0.Beta1

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private Integer id;
	private int paymentStatus;
	private Integer customerId;
	private Integer cashierId;
	private Integer itemId;

	public Payment() {
	}

	public Payment(int paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	public Payment(int paymentStatus, Integer customerId, Integer cashierId, Integer itemId) {
		this.paymentStatus = paymentStatus;
		this.customerId = customerId;
		this.cashierId = cashierId;
		this.itemId = itemId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(int paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Integer getCashierId() {
		return this.cashierId;
	}

	public void setCashierId(Integer cashierId) {
		this.cashierId = cashierId;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

}
